"""workspaces, labels, reminders, task history/dependencies, recurrence, templates

Revision ID: 0ccf73633dde
Revises: ea7bb8e31e0f
Create Date: 2026-07-12 04:22:30.426454

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0ccf73633dde'
down_revision: Union[str, None] = 'ea7bb8e31e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='workspacerole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member')
    )
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_id', name='uq_task_dependency')
    )
    op.create_table('task_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.String(length=500), nullable=True),
    sa.Column('new_value', sa.String(length=500), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_labels',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'label_id')
    )
    op.add_column('projects', sa.Column('is_template', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('projects', sa.Column('workspace_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('projects') as batch_op:
        batch_op.create_foreign_key(
            "fk_projects_workspace_id_workspaces", "workspaces", ["workspace_id"], ["id"]
        )
    task_recurrence_enum = postgresql.ENUM(
        'NONE', 'DAILY', 'WEEKLY', 'MONTHLY', name='taskrecurrence'
    )
    task_recurrence_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('tasks', sa.Column(
        'recurrence', task_recurrence_enum,
        nullable=False, server_default='NONE',
    ))
    op.add_column('tasks', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###

    # Data migration: give every existing user a default workspace and move
    # their existing projects into it, so pre-workspace data keeps working.
    now = datetime.now(timezone.utc)
    users_table = sa.table('users', sa.column('id', sa.Integer))
    workspaces_table = sa.table(
        'workspaces',
        sa.column('id', sa.Integer), sa.column('name', sa.String), sa.column('color', sa.String),
        sa.column('icon', sa.String), sa.column('owner_id', sa.Integer),
        sa.column('created_at', sa.DateTime), sa.column('updated_at', sa.DateTime),
    )
    workspace_members_table = sa.table(
        'workspace_members',
        sa.column('id', sa.Integer), sa.column('workspace_id', sa.Integer),
        sa.column('user_id', sa.Integer), sa.column('role', sa.String),
        sa.column('joined_at', sa.DateTime),
    )
    projects_table = sa.table(
        'projects', sa.column('id', sa.Integer), sa.column('owner_id', sa.Integer),
        sa.column('workspace_id', sa.Integer),
    )

    bind = op.get_bind()
    user_ids = [row[0] for row in bind.execute(sa.select(users_table.c.id))]
    for user_id in user_ids:
        bind.execute(
            workspaces_table.insert().values(
                name="Minha Área de Trabalho", color="#0079bf", icon="briefcase",
                owner_id=user_id, created_at=now, updated_at=now,
            )
        )
        workspace_id = bind.execute(
            sa.select(workspaces_table.c.id)
            .where(workspaces_table.c.owner_id == user_id)
            .order_by(workspaces_table.c.id.desc())
            .limit(1)
        ).scalar_one()
        bind.execute(
            workspace_members_table.insert().values(
                workspace_id=workspace_id, user_id=user_id, role="OWNER", joined_at=now,
            )
        )
        bind.execute(
            projects_table.update()
            .where(projects_table.c.owner_id == user_id)
            .values(workspace_id=workspace_id)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_archived')
    op.drop_column('tasks', 'location')
    op.drop_column('tasks', 'recurrence')
    postgresql.ENUM(name='taskrecurrence').drop(op.get_bind(), checkfirst=True)
    with op.batch_alter_table('projects') as batch_op:
        batch_op.drop_constraint("fk_projects_workspace_id_workspaces", type_='foreignkey')
    op.drop_column('projects', 'workspace_id')
    op.drop_column('projects', 'is_template')
    op.drop_table('task_labels')
    op.drop_table('task_history')
    op.drop_table('task_dependencies')
    op.drop_table('reminders')
    op.drop_table('workspace_members')
    postgresql.ENUM(name='workspacerole').drop(op.get_bind(), checkfirst=True)
    op.drop_table('workspaces')
    op.drop_table('labels')
    # ### end Alembic commands ###
