"""whatsapp connections and messages

Revision ID: 8c340f4d38c6
Revises: 8a54084f6cfe
Create Date: 2026-08-07 13:36:31.891091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8c340f4d38c6'
down_revision: Union[str, None] = '8a54084f6cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DISCONNECTED', 'CONNECTING', 'QR_PENDING', 'CONNECTED', name='whatsappconnectionstatus'), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('monitored_chat_jid', sa.String(length=128), nullable=True),
    sa.Column('monitored_chat_name', sa.String(length=255), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('whatsapp_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['whatsapp_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whatsapp_messages')
    op.drop_table('whatsapp_connections')
    # ### end Alembic commands ###
    sa.Enum(name='whatsappconnectionstatus').drop(op.get_bind(), checkfirst=True)
